### Security ###
debug: false
disable_root: true
ssh_pwauth: false
ssh_deletekeys: true

### User ###
users:
  - name: podmaster
    shell: /bin/bash
    groups: users
    ssh_import_id: None
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${sshkey}

### Package ###
package_update: true
package_upgrade: true
packages:
- podman

### Config ###
write_files:
- encoding: b64
  path: /home/podmaster/nginx/Containerfile
  content: ${containerfile}
  owner: podmaster

runcmd:
- podman build -t nginx-local /home/podmaster/nginx/
- podman run -p 80:80 nginx-local